### ISSUE TITLE
Project structure

### ISSUE THREAD

**Issue by Henje** [HSGI/PiPlan#2]
Thinking about the project structure I think we should have one part(class?) which is a container for the data we transport. To gather the information I would recommend another object which provides the data, so that depending which class we instantiate we can use other sources. For testing we could then also have a static provider with example data. The rest would then be different providers depending on the network conditions and the display. Let me know your thoughts on that.

**Comment by Jan102** [comment]
potato

**Comment by Jan102** [comment]
banana pie

**Comment by Jan102** [comment]
approved
